// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0vSC9gqMihhMAmYEC-gI9o3nouWOShvQ',
    appId: '1:590206005469:web:a51f4e35612c006fb4eb34',
    messagingSenderId: '590206005469',
    projectId: 'house-re-6500a',
    authDomain: 'house-re-6500a.firebaseapp.com',
    storageBucket: 'house-re-6500a.appspot.com',
    measurementId: 'G-WDFB9KDXLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMFsfYrv6P0ppEau8gYv2s1CTt1wA6V-A',
    appId: '1:590206005469:android:ea5fdb7462e47576b4eb34',
    messagingSenderId: '590206005469',
    projectId: 'house-re-6500a',
    storageBucket: 'house-re-6500a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAee0VQfYdUre8mRUeHKnSC2-UrXwP9Njk',
    appId: '1:590206005469:ios:812d2c5399e3d4ebb4eb34',
    messagingSenderId: '590206005469',
    projectId: 'house-re-6500a',
    storageBucket: 'house-re-6500a.appspot.com',
    iosClientId: '590206005469-1beqgtavqhqda4uegtufogdo9o7dtu4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.houseRecord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAee0VQfYdUre8mRUeHKnSC2-UrXwP9Njk',
    appId: '1:590206005469:ios:812d2c5399e3d4ebb4eb34',
    messagingSenderId: '590206005469',
    projectId: 'house-re-6500a',
    storageBucket: 'house-re-6500a.appspot.com',
    iosClientId: '590206005469-1beqgtavqhqda4uegtufogdo9o7dtu4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.houseRecord',
  );
}
